name: Bug report
description: Report a bug or regression
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you see and what did you expect instead?
      placeholder: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and any relevant input data.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      description: Paste relevant `storage/logs/laravel.log` lines or stack traces.
      render: shell
    validations:
      required: false

  - type: input
    id: env
    attributes:
      label: Environment
      description: local / staging / production
      placeholder: production
    validations:
      required: false


