<?php

return [
    'contracts' => [
        'shared-ga4-baseline-v1' => [
            'name' => 'Shared GA4 Baseline',
            'version' => 'v1',
            'contract_type' => 'ga4_web',
            'status' => 'active',
            'scope' => 'portfolio_default',
            'source_repo' => 'MM-Google',
            'source_path' => 'docs/event-taxonomy.md',
            'notes' => 'Shared baseline event model for GA4 sites unless a documented exception overrides it.',
            'contract' => [
                'recommended_events' => [
                    'page_view',
                    'session_start',
                    'scroll',
                    'view_search_results',
                    'select_content',
                    'generate_lead',
                    'phone_click',
                    'email_click',
                    'form_submit',
                    'booking_start',
                    'booking_complete',
                ],
                'key_events' => [
                    'generate_lead',
                    'phone_click',
                    'form_submit',
                    'booking_start',
                    'booking_complete',
                ],
                'standard_parameters' => [
                    'site_key',
                    'brand',
                    'lead_type',
                    'form_name',
                    'page_type',
                    'push_channel',
                    'push_template',
                    'crm_lead_id',
                    'job_id',
                    'user_type',
                ],
                'custom_dimensions' => [
                    [
                        'parameter_name' => 'site_key',
                        'display_name' => 'Site Key',
                        'description' => 'Internal site identifier',
                        'scope' => 'EVENT',
                    ],
                    [
                        'parameter_name' => 'lead_type',
                        'display_name' => 'Lead Type',
                        'description' => 'Lead capture intent',
                        'scope' => 'EVENT',
                    ],
                    [
                        'parameter_name' => 'push_channel',
                        'display_name' => 'Push Channel',
                        'description' => 'Push provider or channel',
                        'scope' => 'EVENT',
                    ],
                ],
                'naming_rules' => [
                    'lowercase snake_case only',
                    'prefer reusable semantic names over campaign-specific names',
                    'do not encode site names into event names',
                    'prefer parameters over separate events unless the business flow is intentionally split and stable',
                ],
                'joining_guidance' => [
                    'pass client_id or a first-party session identifier where lawful',
                    'capture crm_lead_id after lead creation',
                    'propagate booking or job IDs when a booking is confirmed',
                    'keep site_key on every custom event',
                ],
            ],
            'assignment' => [
                'match' => 'ga4_properties',
                'exclude_slugs' => ['moveroo-com-au'],
                'rollout_status' => 'defined',
                'notes' => 'Backfilled from MM-Google shared taxonomy. Instrumentation and verification status should be promoted with evidence, not assumed.',
            ],
        ],
        'moveroo-full-funnel-v1' => [
            'name' => 'Moveroo Full Funnel',
            'version' => 'v1',
            'contract_type' => 'ga4_web_and_backend',
            'status' => 'active',
            'scope' => 'documented_exception',
            'source_repo' => 'MM-Google',
            'source_path' => 'docs/moveroo-integration.md',
            'notes' => 'Moveroo exception covering the apex site, quote subdomains, and Measurement Protocol backend lifecycle events.',
            'contract' => [
                'website_events' => [
                    'quote_household_click',
                    'quote_vehicle_click',
                    'phone_click',
                    'form_submit',
                ],
                'quote_subdomain_events' => [
                    'household_quote_started',
                    'vehicle_quote_started',
                    'household_generate_lead',
                    'vehicle_generate_lead',
                    'household_booking_complete',
                    'vehicle_booking_complete',
                ],
                'backend_measurement_protocol_events' => [
                    'lead_created',
                    'lead_qualified',
                    'job_booked',
                    'job_completed',
                    'push_sent',
                    'push_delivered',
                    'push_opened',
                    'push_clicked',
                ],
                'key_events' => [
                    'quote_household_click',
                    'quote_vehicle_click',
                    'phone_click',
                    'form_submit',
                    'household_generate_lead',
                    'vehicle_generate_lead',
                    'household_booking_complete',
                    'vehicle_booking_complete',
                ],
                'standard_parameters' => [
                    'site_key',
                    'ga_client_id',
                    'crm_lead_id',
                    'job_id',
                ],
                'implementation_guidance' => [
                    'one shared client-side tracking helper across apex domain and quote subdomains',
                    'one shared backend event sender for Measurement Protocol',
                    'one consistent site_key and quote-flow naming model',
                    'one GA4 property for the full customer journey',
                ],
                'reporting_kpis' => [
                    'leads by source',
                    'bookings by source',
                    'lead-to-booking rate',
                    'push sent-to-open rate',
                    'push open-to-booking rate',
                    'revenue or job value by acquisition source',
                ],
            ],
            'assignment' => [
                'property_slugs' => ['moveroo-com-au'],
                'rollout_status' => 'defined',
                'notes' => 'Applies to moveroo.com.au plus its quote-subdomain journey. Quote runtime instrumentation still needs explicit verification in the maintained Laravel app.',
            ],
        ],
    ],
];
